clear;clc;close all;
% --------- SDR configuration ----------
fc = 2.45e9;
decimFact = 32; % USRP decimation factor 
usrpMasterClk = 100e6; % USRP master clock in Hz
samplesRate = usrpMasterClk/decimFact;
frameLen = 8192; % samples per frame
RX = comm.SDRuReceiver('Platform','N200/N210/USRP2',...
    'IPAddress', '192.168.10.6',...
    'CenterFrequency', fc,...
    'Gain', 30,...
    'DecimationFactor', decimFact,...
    'MasterClockRate',  usrpMasterClk,...
    'SamplesPerFrame', frameLen); % The current config results in output sample rate of 3.125 MHz
% --------- Modulation config -----------
alpha = 0.45;
sps = 4;
modType = 'qpsk';
% --------- Reception offline processing --------
Tsec = 4; % capture time in seconds
totalSampN = round(samplesRate*Tsec); % total collected samples
rxData = complex(zeros(totalSampN,1));

% --------- Visualization config ---------
scope = spectrumAnalyzer(...
    'Name',             'Base Band Spectrum',...
    'Title',            'Baseband spectrum', ...
    'Method',           'filter-bank', ...
    'SpectrumType',     'Power density', ...
    'FrequencySpan',    'Full', ...
    'SampleRate',       samplesRate, ...
    'FrequencyOffset',  0, ...
    'FFTLength',        1024,...
    'YLimits',          [-120 40], ...
    'YLabel',           'Magnitude-squared, dB', ...
    'Position',         figposition([50 30 30 40]));
scope.ShowLegend   = true;
scope.ChannelNames = {'CFO compensated', 'Uncompensated'};

% -------- RX Digital Signal Processing -------
agc = comm.AGC( ...
    AdaptationStepSize = 1e-3, ...
    MaxPowerGain       = 30 );

% Very important: this object is able to recover one side 
% frequency offset. check the output with scope function
freqComp = comm.CoarseFrequencyCompensator( ...
    Modulation=modType, ...
    SampleRate=samplesRate, ...
    FrequencyResolution=1); 

rxRRC = comm.RaisedCosineReceiveFilter( ...
    Shape="Square root", ...
    RolloffFactor=alpha, ...
    InputSamplesPerSymbol=sps, ...
    DecimationFactor=1, ...
    FilterSpanInSymbols=11);

symSync = comm.SymbolSynchronizer( ...
    TimingErrorDetector="Zero-Crossing (decision-directed)", ...
    SamplesPerSymbol=sps, ...
    NormalizedLoopBandwidth=0.001, ...   % range between 0 and 1
    DampingFactor=1, ...
    DetectorGain=2.7);

carSync = comm.CarrierSynchronizer( ...
    Modulation="QPSK", ...
    SamplesPerSymbol=1, ...
    NormalizedLoopBandwidth=0.01, ...     % tune 0.002–0.02
    DampingFactor=1.0);

% -------- Start Receiving -----------
overRuncount = 0;
k = 1;

disp("Recording...");
tStart = tic;
while toc(tStart) < Tsec
    [rxBB,dateLen,overrun] = RX();
    %scope(rxBB);
    rxData((k-1)*frameLen+(1:frameLen)) =  rxBB;
    overRuncount = overRuncount + any(overrun);
    k = k + 1;
end

%release(scope);
release(RX);
rxData = rxData(2*frameLen:(k-1)*frameLen); % Exclude the data part

% ---------- Post processing ----------
rxData = agc(rxData);
[rxCompensated,estFreqOffset] = freqComp(rxData);
scope([rxCompensated,rxData]);
release(scope);

rxSymb = rxRRC(rxCompensated(frameLen+1:end)); % drop the head otherwise it can not lock since there is a large amplitude variation at the begining
scatterplot(rxSymb(frameLen:2*frameLen)); % It is all over the place
rxSynced = symSync(rxSymb);
scatterplot(rxSynced(frameLen:2*frameLen)); % It is around the circle since there is a residual phase shift

rxFinal = carSync(rxSynced);
scatterplot(rxFinal(frameLen:2*frameLen)); % It is mostly concentrated at the correct constellation location