clear;clc;close all;

fc = 2.45e9;
scope = spectrumAnalyzer(...
    'Name',             'Base Band Spectrum',...
    'Title',            'Baseband spectrum', ...
    'Method',           'filter-bank', ...
    'SpectrumType',     'Power density', ...
    'FrequencySpan',    'Full', ...
    'SampleRate',       1e6, ...
    'FrequencyOffset',  0, ...
    'FFTLength',        1024,...
    'YLimits',          [-120 40], ...
    'YLabel',           'Magnitude-squared, dB', ...
    'Position',         figposition([50 30 30 40]));

RX = comm.SDRuReceiver('Platform','N200/N210/USRP2',...
    IPAddress='192.168.10.6',...
    CenterFrequency=fc,...
    DecimationFactor=100,...
    MasterClockRate=100e6,...
    SamplesPerFrame=1024); % The current config results in output sample rate of 1MHz

Tsec = 20;
disp('RX host: starting receiption...');
tStart = tic;
while toc(tStart) < Tsec
    rxBB = RX();
    scope(rxBB);
end
disp('RX host: done.');
release(RX);
release(scope);
